.TH DWM 1 dwm\-VERSION
.SH NAME
dwm \- dynamischer Fenstermanager (Luke Smith <https://lukesmith.xyz>'s Version)
.SH SYNOPSIS
.B dwm
.RB [ \-v ]
.SH BESCHREIBUNG
dwm ist ein dynamischer Fenstermanager für X.
.P
dwm ordnet Fenster nach Aktualität und Priorität. Während die Layouts von dwm
sich ändern können, wird das aktuellste "Master"-Fenster immer in der
hervorgehobenen Position angezeigt. Es gibt Tastenkombinationen, um durch
Fenster zu wechseln und Fenster in die Master-Position zu befördern.
.P
Fenster werden nach Tags gruppiert. Jedes Fenster kann mit einem oder mehreren
Tags versehen werden. Wenn bestimmte Tags ausgewählt werden, werden alle Fenster
mit diesen Tags angezeigt.
.P
Jeder Bildschirm enthält eine kleine Statusleiste, die alle verfügbaren Tags, das
Layout, den Titel des fokussierten Fensters und den Text anzeigt, der aus der
Root-Fenstereigenschaft ausgelesen wird, wenn der Bildschirm fokussiert ist.
Ein schwebendes Fenster wird durch ein leeres Quadrat angezeigt, und ein
maximiertes schwebendes Fenster wird durch ein ausgefülltes Quadrat vor dem
Fenstertitel angezeigt. Die ausgewählten Tags werden durch eine andere Farbe
markiert. Die Tags des fokussierten Fensters werden durch ein ausgefülltes
Quadrat in der oberen linken Ecke markiert. Die Tags, die auf eines oder
mehrere Fenster angewendet wurden, werden durch ein leeres Quadrat in der
oberen linken Ecke angezeigt.
.P
dwm zeichnet einen kleinen Rahmen um Fenster, um den Fokuszustand anzuzeigen.
.SH OPTIONEN
.TP
.B \-v
gibt Versionsinformationen auf stderr aus und beendet sich dann.
.SH NUTZUNG
.SS Statusleiste
.TP
.B X Root-Fenstername
wird gelesen und im Statusbereich angezeigt. Er kann mit dem Befehl
.BR xsetroot (1)
gesetzt werden.
.TP
.B Linksklick
Klicken auf ein Tag-Label, um alle Fenster mit diesem Tag anzuzeigen. Ein Klick auf das
Layout-Label wechselt zwischen Kachel- und Schwebezustand.
.TP
.B Rechtsklick
Klicken auf ein Tag-Label fügt alle Fenster mit diesem Tag zur Ansicht hinzu oder
entfernt sie davon.
.TP
.B Super\-Linksklick
Klicken auf ein Tag-Label wendet das Tag auf das fokussierte Fenster an.
.TP
.B Super\-Rechtsklick
Klicken auf ein Tag-Label fügt dieses Tag zum fokussierten Fenster hinzu oder
entfernt es davon.
.SS Tastenkombinationen
.TP
.B Super\-Return
Startet ein Terminal,
.BR st(1).
.TP
.B Super\-d
Startet
.BR dmenu(1),
um andere Programme zu starten.
.TP
.B Super\-Grave
Startet
.BR dmenuunicode(1),
um Emoji auszuwählen.
.TP
.B Super\-Minus/Plus, Super\-Shift\-Minus/Plus
Verringert/erhöht die Lautstärke um 5 bzw. 15.
.TP
.B Super\-b
Schaltet die Statusleiste ein oder aus.
.TP
.B Super\-q
Schließt das fokussierte Fenster.
.TP
.B Super\-t/T
Setzt das Kachel/Bstack-Layout.
.TP
.B Super\-f
Wechselt in den Vollbildmodus des Fensters.
.TP
.B Super\-F
Wechselt das Layout in den Schwebezustand.
.TP
.B Super\-y/Y
Setzt das Fibonacci-Spiral/Dwindle-Layout.
.TP
.B Super\-u/U
Setzt das Layout "Zentrierter Master".
.TP
.B Super\-i/I
Setzt das Layout "Zentrierter Master" oder "Schwebender Master".
.TP
.B Super\-Leertaste
Zoomt/Wechselt das fokussierte Fenster zum/vom Master-Bereich.
.TP
.B Super\-j/k
Fokussiert das nächste/vorherige Fenster.
.TP
.B Super\-Shift\-j/k
Verschiebt das ausgewählte Fenster nach unten/oben im Stapel.
.TP
.B Super\-o/O
Erhöht/verringert die Anzahl der Fenster im Master-Bereich.
.TP
.B Super\-l
Erhöht die Größe des Master-Bereichs.
.TP
.B Super\-h
Verringert die Größe des Master-Bereichs.
.TP
.B Super\-Shift\-Leertaste
Wechselt das fokussierte Fenster zwischen Kachel- und Schwebezustand.
.TP
.B Super\-Tab
Wechselt zu den zuletzt ausgewählten Tags.
.TP
.B Super\-g
Wechselt zum vorherigen Tag.
.TP
.B Super\-Shift\-g
Verschiebt das ausgewählte Fenster zum vorherigen Tag.
.TP
.B Super\-;
Wechselt zum nächsten Tag.
.TP
.B Super\-Shift\-;
Verschiebt das ausgewählte Fenster zum nächsten Tag.
.TP
.B Super\-BildAuf/BildAb
Wechselt zum vorherigen/nächsten Tag.
.TP
.B Super\-Shift\-BildAuf/BildAb
Verschiebt das ausgewählte Fenster zum vorherigen/nächsten Tag.
.TP
.B Super\-a
Schaltet die Fensterabstände um.
.TP
.B Super\-z
Erhöht die Abstände zwischen den Fenstern.
.TP
.B Super\-x
Verringert die Abstände zwischen den Fenstern.
.TP
.B Super\-Shift\-[1..n]
Wendet das n-te Tag auf das fokussierte Fenster an.
.TP
.B Super\-Shift\-0
Wendet alle Tags auf das fokussierte Fenster an.
.TP
.B Super\-Control\-Shift\-[1..n]
Fügt das n-te Tag dem fokussierten Fenster hinzu oder entfernt es davon.
.TP
.B Super\-[1..n]
Zeigt alle Fenster mit dem n-ten Tag an.
.TP
.B Super\-0
Zeigt alle Fenster mit irgendeinem Tag an.
.TP
.B Super\-Control\-[1..n]
Fügt alle Fenster mit dem n-ten Tag zur Ansicht hinzu oder entfernt sie davon.
.TP
.B Super\-Shift\-q
Beendet dwm.
.TP
.B Mod1\-Control\-Shift\-q
Zeigt ein Menü zum Neustarten/Beenden/Neustarten/Herunterfahren an.
.SS Mausbefehle
.TP
.B Super\-Linksklick
Bewegt das fokussierte Fenster beim Ziehen. Kachel-Fenster werden in den Schwebezustand versetzt.
.TP
.B Super\-Mittelklick
Wechselt das fokussierte Fenster zwischen Schweben und Kachel.
.TP
.B Super\-Rechtsklick
Ändert die Größe des fokussierten Fensters beim Ziehen. Kachel-Fenster werden in den Schwebezustand versetzt.
.SH ANPASSUNG
dwm wird angepasst, indem eine benutzerdefinierte config.h erstellt und der Quellcode neu kompiliert wird. Dies hält dwm schnell, sicher und einfach.
.SH SIGNALS
.TP
.B SIGHUP - 1
Startet den dwm-Prozess neu.
.TP
.B SIGTERM - 15
Beendet den dwm-Prozess sauber.
.SH SIEHE AUCH
.BR dmenu (1),
.BR st (1)
.SH PROBLEME
Java-Anwendungen, die das XToolkit/XAWT-Backend verwenden, zeigen möglicherweise nur graue Fenster an. Das XToolkit/XAWT-Backend bricht die ICCCM-Konformität in den neueren Versionen von JDK 1.5 und frühen JDK 1.6-Versionen, da es davon ausgeht, dass ein Reparenting-Windows-Manager verwendet wird. Mögliche Workarounds bestehen darin, JDK 1.4 zu verwenden (das nicht das XToolkit/XAWT-Backend enthält) oder die Umgebungsvariable
.BR AWT_TOOLKIT=MToolkit
zu setzen (um das ältere Motif-Backend zu verwenden) oder
.B xprop -root -f _NET_WM_NAME 32a -set _NET_WM_NAME LG3D
oder
.B wmname LG3D
auszuführen (um einen nicht-reparentierenden Fenstermanager vorzutäuschen, den das XToolkit/XAWT-Backend erkennen kann) oder bei der Verwendung von OpenJDK die Umgebungsvariable
.BR _JAVA_AWT_WM_NONREPARENTING=1
zu setzen.
.SH FEHLER
Alle Fehlerberichte mit einem Patch an hackers@suckless.org senden.
